config/routes.rb
Rails.application.routes.draw do

  root 'pictures#index'
  post '/picture/:id/like' => 'pictures#like', as: :like

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :picture
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  has_many :likes

  def update_likes(user)
    user_liked?(user) ? unlike(user) : like(user)
  end

  def likes_message(user)
    if !user_liked?(user)
      "<strong>#{self.likes.count} people</strong> like this image".html_safe
    else
      "<strong>You</strong> and <strong>#{self.likes.count - 1} other people</strong> like this image".html_safe
    end
  end

  def heart_class(user)
    if user_liked?(user)
      "glyphicon glyphicon-heart red-heart"
    else
      "glyphicon glyphicon-heart grey-heart"
    end
  end

  private
  def user_liked?(user)
    self.likes.where(user: user).any?
  end

  def like(user)
    self.likes.create(user_id: user.id)
  end

  def unlike(user)
    self.likes.find_by(user_id: user.id).destroy
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pictures
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception

  helper_method def current_user
    @current_user = User.find_by(name: "You")
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.all
  end

  def like
    @picture = Picture.find(params[:id])
    @picture.update_likes(current_user)
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<div class="container">
  <div class="feed-wrapper">

    <!-- SHOW ALL OF THE PICTURES -->
    <% @pictures.each do |picture| %>
      <!-- INDIVIDUAL IMAGE -->
      <div class="image-wrapper">

        <div class="insta-img">
          <%= image_tag("#{picture.url}", width: "500") %>
        </div>

        <div class="bottom-content">

          <div class="like">
            <%= link_to like_path(id: picture.id), method: :post do %>
              <div class="like-btn text-center" picture_id="<%= picture.id %>">
                <span class="<%= picture.heart_class(current_user) %>"></span>
              </div>
            <% end %>
            <div class="likes-message"><%= picture.likes_message(current_user) %></div>
          </div> <!-- end like -->

          <div class="user">
            <div><%= image_tag("#{picture.user.profile_pic}", width: "50") %></div>
            <div class="description">
              <div>
                <strong><%= picture.user.name %></strong> 
                <%= picture.description %>
              </div>
            </div>
          </div> <!-- end user -->

        </div> <!-- end bottom-content -->

      </div><!-- end INDIVIDUAL IMAGE -->
    <% end %>
    
  </div> <!-- end feed-wrapper -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FLATstagram</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="logo text-center">
        <%= image_tag("flinstagram.png", width: "200") %>
      </div>
    </div>
  </nav>

  <%= yield %>

  <footer class="text-center">
    <h4>Made with ♡ at <%= link_to "The Flatiron School", "http://flatironschool.com" %></h4>
  </footer>

</body>
</html>